steps:
- task: Gulp@0
  displayName: 'Test'
  inputs:
    targets: 'test'
  env:
    DOCKER_UNAVAILBLE: 1
    SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
    SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
    SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)

- template: publish-test-results.yml
